"""Markdown report writer — generates a human-readable EDA summary."""

import logging
import os
from datetime import datetime

logger = logging.getLogger(__name__)


def write_report(source_file: str, df, results: dict, chart_paths: list, output_dir: str) -> str:
    """Write a Markdown summary report of the EDA run.

    Args:
        source_file: Path to the original data file.
        df: Cleaned DataFrame.
        results: Analysis results dictionary.
        chart_paths: List of generated chart file paths.
        output_dir: Directory to save the report.

    Returns:
        Path to the written report file.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = os.path.basename(source_file)

    lines = [
        f"# EDA Report — {filename}",
        f"**Generated:** {now}  ",
        f"**Source:** `{source_file}`",
        "",
        "---",
        "",
        "## Dataset Overview",
        f"- **Total rows:** {results.get('total_rows', 'N/A'):,}",
        f"- **Total columns:** {results.get('total_columns', 'N/A')}",
        f"- **Missing values:** {results.get('missing_values', 'N/A'):,} ({results.get('missing_pct', 0)}%)",
        f"- **Columns:** `{'`, `'.join(results.get('column_names', []))}`",
        "",
    ]

    if "date_min" in results:
        lines += [
            "## Date Range",
            f"- **From:** {results['date_min']}",
            f"- **To:** {results['date_max']}",
            "",
        ]

    if "avg_duration" in results:
        stats = results.get("duration_stats", {})
        lines += [
            "## Video Duration",
            f"- **Average:** {results['avg_duration']} seconds",
            f"- **Min:** {stats.get('min', 'N/A')}",
            f"- **Max:** {stats.get('max', 'N/A')}",
            f"- **Std Dev:** {round(stats.get('std', 0), 2)}",
            "",
        ]

    if "top_pages" in results:
        lines += ["## Top Pages by Video Count", ""]
        for page, count in results["top_pages"].items():
            lines.append(f"- **{page}:** {count:,} videos")
        lines.append("")

    if chart_paths:
        lines += ["## Charts Generated", ""]
        for path in chart_paths:
            lines.append(f"- `{os.path.basename(path)}`")
        lines.append("")

    lines += [
        "---",
        "",
        "*Generated by EDA Toolkit · [Code Alchemist Labs](https://codealchemistlabs.com)*",
    ]

    report_path = os.path.join(output_dir, "report.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Report written to: {report_path}")
    return report_path
